language: android
sudo: false
jdk: oraclejdk8

android:
  components:
    - platform-tools
    - tools
    - build-tools-24.0.2
    - android-23

script:
    - chmod +x ./gradlew

notifications:
  slack:
    rooms:
      - kpi-integration-2016:zvKvQcOYpf5YKTKXeIyl9Tzs#{xunta}