language: android
sudo: false
jdk: oraclejdk8
env:
  matrix:
    - ANDROID_TARGET=android-23 ANDROID_ABI=armeabi-v7a
android:
  components:
    - platform-tools
    - tools
    - build-tools-24.0.2
    - android-23
    - extra-android-m2repository
    - extra-google-m2repository
    - sys-img-armeabi-v7a-android-23
before_install:
    - chmod +x gradlew

before_script:
    - emulator -avd test -no-skin -no-audio -no-window &

script:
    - ./gradlew check -PdisablePreDex --continue --stacktrace
    - android-wait-for-emulator
    - adb devices
    - adb shell input keyevent 82 &
    - ./gradlew connectedAndroidTest -PdisablePreDex --continue --stacktrace